### ISSUE TITLE
stmf0xx.h comment contains non-utf-8 character

### ISSUE THREAD

**Issue by ghost** [STMicroelectronics/cmsis_device_f0#3]
cmsis_device_f0/Include/stm32f0xx.h:60:  * - Product miscellaneous configuration: assert macros, �

clang-16 warns about invalid utf-8 characters in comments:
cmsis_device_f0/Include/stm32f0xx.h:60:59: warning: invalid UTF-8 in comment [-Winvalid-utf8]
[build]   * - Product miscellaneous configuration: assert macros, <85>

assuming a UTF-8 locale the following command can be used to find non-utf8 chars:
find STMicroelectronics -type f | xargs grep -anxv '.*'

**Comment by HBOSTM** [comment]
ST Internal Reference: 160255

**Comment by corrigami** [comment]
Any updates on this? Seems like a fairly trivial issue to change three apostrophe's and an ellipsis in some comments. Thank you.

**Comment by ALABSTM** [comment]
Hi @JanHildenbrandBosch,

Please excuse this delay to reply. The fix has just been uploaded. Thank you again for having reported.

With regards,

**Comment by ALABSTM** [comment]
Fixed in commit 56cf85c7e2f8ecdf7f2093b77edab28c12ebe96d
